# Use root/example as user/password credentials
version: '3.1'
services:

  payment-service:
      image: "payment-service"
      build: 
        context: .
        dockerfile: PaymentService.Dockerfile
      expose:
          - "9998"
      links:
          - mongo-payment
          - rabbitmq
      depends_on:
          - mongo-payment
          - rabbitmq
      environment: 
          MONGOCONNECTION: "mongodb://mongo-payment:27017"
          DATABASENAME: "Payments"
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: http://+:9998
          RABBITCONNECTION: host=rabbitmq;timeout=90


  mongo-payment:
      image: 'bitnami/mongodb:latest'
      expose: 
        - '27017'

  order-service:
      image: "order-service"
      build: 
        context: .
        dockerfile: OrderService.Dockerfile
      expose:
          - "9999"
      links:
          - mongo-order
          - rabbitmq
      depends_on:
          - mongo-order
      environment: 
          MONGOCONNECTION: "mongodb://mongo-order:27017"
          DATABASENAME: "Orders"
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: http://+:9999
          RABBITCONNECTION: host=rabbitmq

  mongo-order:
      image: 'bitnami/mongodb:latest'
      expose: 
        - '27017'
      
  
  frontend:
      image: "frontend"
      build: 
        context: .
        dockerfile: FrontEnd.Dockerfile
      ports:
          - "5020:5020"
      environment: 
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: http://+:5020
          ORDERURI: "http://order-service:9999"
          PAYMENTURI: "http://payment-service:9998"
  
  rabbitmq:
      image: rabbitmq:3-management
      expose:
        - "5672"
      ports:
        - "8080:15672"